Test gqlgen generate in CI

diff --git a/.github/workflows/check-init b/.github/workflows/check-init
--- a/.github/workflows/check-init
+++ b/.github/workflows/check-init
@@ -5,10 +5,17 @@ set -euo pipefail
 gqlgen_dir=$(pwd)
 cd $(mktemp -d)
 go mod init inittest
+printf '// +build tools\npackage tools\nimport _ "github.com/99designs/gqlgen"' | gofmt > tools.go
+go mod tidy
 go mod edit -replace=github.com/99designs/gqlgen="$gqlgen_dir"
-go get -d github.com/99designs/gqlgen
+go mod tidy
 
-if ! go run github.com/99designs/gqlgen init &>/dev/null ; then
+if ! go run github.com/99designs/gqlgen init ; then
     echo "gqlgen init failed"
+    exit 125
+fi
+
+if ! go run github.com/99designs/gqlgen generate ; then
+    echo "gqlgen generate failed"
     exit 125
 fi
