Go back to junit format
Signed-off-by: Steve Coffman <steve@khanacademy.org>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,10 +33,17 @@ jobs:
         run: |
           set -euo pipefail
           go mod download
-          gotestsum --format=github-actions -- -race ./... -trimpath
+          gotestsum --junitfile report.xml --format-icons=hivis --format=github-actions -- -race ./... -trimpath
       - name: Example tests
         shell: bash
         run: |
           cd _examples
           go mod download
-          gotestsum --format-icons=hivis --format=github-actions -- -race ./... -trimpath
+          gotestsum --junitfile ../go_examples_report.xml --format-icons=hivis --format=github-actions -- -race ./... -trimpath
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: |
+            report.xml
+            go_examples_report.xml
