Try some more fun things
Signed-off-by: Steve Coffman <steve@khanacademy.org>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,25 +32,45 @@ jobs:
           go-version: ${{ matrix.go }}
       # Install gotestsum on the VM running the action.
       - name: Setup gotestsum
-        uses: autero1/action-gotestsum@v2.0.0
-        with:
-          gotestsum_version: v1.12.0
+        run: go install gotest.tools/gotestsum@latest
       - name: Core tests
         shell: bash
         run: |
           set -euo pipefail
           go mod download
-          gotestsum --junitfile report.xml --format-icons=hivis --format=pkgname-and-test-fails -- -race ./... -trimpath
+          gotestsum --jsonfile go_test.json --junitfile report.xml --format-icons=hivis --format=pkgname-and-test-fails -- -race ./... -trimpath
       - name: Example tests
         shell: bash
+        if: success() || failure() # always run even if the previous step fails
         run: |
           cd _examples
           go mod download
           gotestsum --junitfile ../go_examples_report.xml --format-icons=hivis --format=github-actions -- -race ./... -trimpath
       - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
+        uses: mikepenz/action-junit-report@v4.3.0
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: |
             report.xml
             go_examples_report.xml
+      - name: Annotate tests
+        if: success() || failure() # always run even if the previous step fails
+        uses: guyarb/golang-test-annotations@v0.8.0
+        with:
+          test-results: go_test.json
+      - name: Publish go-test-action Report
+        if: success() || failure() # always run even if the previous step fails
+        uses: robherley/go-test-action@v0.4.1
+        with:
+          # Parse an exisiting [test2json](https://pkg.go.dev/cmd/test2json) file, instead of executing go test.
+          # Will always exit(0) on successful test file parse.
+          # Optional. No default
+          fromJSONFile: go_test.json
+      - name: Publish Test Summary Report
+        uses: test-summary/action@v2.3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          paths: |
+            report.xml
+            go_examples_report.xml
+          show: "fail, skip"
